server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

jwt:  
  secretKey: asdfladf98a7df89aysf8d9yasiudfha9s87dfa89syudhfa98sdfyaisuhdfa98sfy


spring: 
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user-service/**
          filters:
            - StripPrefix=2

        - id: posts-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/v1/post-service/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: connections-service
          uri: lb://CONNECTION-SERVICE
          predicates:
            - Path=/api/v1/connection-service/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter
