

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring: 
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user-service/**
          filters:
            - StripPrefix=2

        - id: posts-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/v1/post-service/**
          filters:
            - StripPrefix=2

        - id: connections-service
          uri: lb://CONNECTION-SERVICE
          predicates:
            - Path=/api/v1/connection-service/**
          filters:
            - StripPrefix=2
