spring:
  application:
    name: post-service
  datasource:
    url: jdbc:postgresql://localhost:5432/linkedin_posts_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      
server:
  port: 9010
  servlet:
    context-path: /post-service

  
