spring:
  application:
    name: post-service
  datasource:
    url: jdbc:postgresql://posts-db-service:5432/linkedin_posts_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: kafka-service:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      
server:
  port: 9010
  servlet:
    context-path: /post-service

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka