spring:
  application:
    name: connection-service
  kafka:
    bootstrap-servers: kafka-service:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  neo4j:
    uri: bolt://connection-db-service:7687
    authentication:
      username: neo4j
      password: password

server:
  servlet:
    context-path: /connection-service
  port: 9030

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

  